version: 2
jobs:
   build:
     docker:
       - image: circleci/buildpack-deps:latest
     steps:
       - checkout
       - run: sudo apt install -y texlive-base texlive-xetex texlive-cjk latexmk
       - run: for i in simhei.ttf simkai.ttf simsun.ttc simsunb.ttf simfang.ttf; do wget -P fonts/ https://xugr.keybase.pub/static/fonts/$i; done
       - run: mkdir -p ~/.local/share/fonts && cp -r fonts/* ~/.local/share/fonts/
       - run: fc-cache -rv
       - run: latexmk -xelatex -interaction=nonstopmode -file-line-error report.tex